Calculs inexacts en algèbre linéaire

In [1]:
def cond_hilbert(n): 
    A = matrix(QQ, [[1/(i+j-1) for j in [1..n]] for i in [1..n]])
    return A.norm(Infinity) * (A^-1).norm(Infinity)

In [5]:
for n in range(2,6):
    print(n, cond_hilbert(n))

(2, 27.0)
(3, 748.0)
(4, 28374.999999999996)
(5, 943656.0)


In [8]:
def erreur_diff(n):     
    x = vector(QQ,[1 for i in range(0,n)]) 
    A = matrix(QQ, [[1/(i+j-1) for j in [1..n]] for i in [1..n]])
    y = A*x 
    A[n-1,n-1] = (1/(2*n-1))*(1+1/(10^5)) # perturbe la matrice 
    sol = A\y 
    diff = max(float(sol[i]-x[i]) for i in range(0,n))
    return(diff)

In [12]:
for n in range(4,36,4):
    print(n, erreur_diff(n))

(4, 0.00597609561752988)
(8, 3.470535307793226)
(12, 17.6785678760495)
(16, 63.281609195139296)
(20, 269.3745173745173)
(24, 1122.8830260918887)
(28, 4452.822062787379)
(32, 20034.347742129325)


In [13]:
n = 8 
A = matrix(RR, [[1/(i+j-1) for j in [1..n]] for i in [1..n]]) 
x = vector(RR, [1 for i in range(0,n)]) 
y = A*x 
s = A.solve_right(y) 
diff = [float(s[i]-x[i]) for i in range(0,n)]

Matrices pleines

In [14]:
n = 20; cout = (n+1)*factorial(n); cout

51090942171709440000

In [15]:
v = 3*10^9
print "%3.3f"%float(cout/v/3600/24/365)

540.028


In [16]:
A = matrix(RDF, [[-1,2],[3,4]]) 
b = vector(RDF, [2,3]) 
x = A\b; x

(-0.20000000000000018, 0.9000000000000001)

In [17]:
x = A.solve_right(b)

In [18]:
A = matrix(RDF, [[-1,2],[3,4]]) 
P, L, U = A.LU()

In [19]:
A = random_matrix(RDF, 1000) 
b = vector(RDF, range(1000))

In [20]:
%time A.LU()

CPU times: user 44 ms, sys: 20 ms, total: 64 ms
Wall time: 65.9 ms


(1000 x 1000 dense matrix over Real Double Field,
 1000 x 1000 dense matrix over Real Double Field,
 1000 x 1000 dense matrix over Real Double Field)

In [21]:
%time x = A.solve_right(b)

CPU times: user 36 ms, sys: 4 ms, total: 40 ms
Wall time: 39.3 ms


In [22]:
m = random_matrix(RDF, 10) 
A = transpose(m)*m 
C = A.cholesky()

In [23]:
A = random_matrix(RDF,6,5) 
Q, R = A.QR()

In [24]:
A = matrix(RDF, [[1,3,2],[1,2,3],[0,5,2],[1,1,1]]) 
U, Sig, V = A.SVD() 
A1 = A - U*Sig*transpose(V); A1

[ 2.220446049250313e-16                    0.0 -4.440892098500626e-16]
[3.3306690738754696e-16 -4.440892098500626e-16 -4.440892098500626e-16]
[-9.457978716560331e-16 1.7763568394002505e-15 -4.440892098500626e-16]
[ 4.440892098500626e-16 -8.881784197001252e-16 -4.440892098500626e-16]

In [0]:
A = matrix(RDF, [[1,3,2],[1,4,2],[0,5,2],[1,3,2]]) 
b = vector(RDF, [1,2,3,4]) 
Z = transpose(A)*A 
C = Z.cholesky()
R = transpose(A)*b 
Z.solve_right(R)

In [25]:
A = matrix(RDF, [[1,3,2],[1,4,2],[0,5,2],[1,3,2]]) 
b = vector(RDF, [1,2,3,4]) 
Q, R = A.QR() 
R1 = R[0:3,0:3]
b1 = transpose(Q)*b 
c = b1[0:3]
R1.solve_right(c)

(-1.499999999999999, -0.49999999999999867, 2.749999999999997)

In [26]:
Z = A.transpose()*A 
Z.norm(Infinity)*(Z^-1).norm(Infinity)

1992.3750000000168

In [27]:
A = matrix(RDF, [[1,3,2],[1,3,2],[0,5,2],[1,3,2]]) 
b = vector(RDF, [1,2,3,4])
U, Sig, V = A.SVD() 
m = A.ncols()
x = vector(RDF, [0]*m) 
lamb = vector(RDF, [0]*m)

In [28]:
for i in range(0,m): 
    s = Sig[i,i]
    if s < 1e-12: 
        break
    lamb[i] = U.column(i)*b / s 
x = V*lamb; x

(0.2370370370370367, 0.4518518518518521, 0.3703703703703702)

In [29]:
m = 3 
[ Sig[i,i] for i in range(0,m) ]

[8.309316833256451, 1.3983038884881154, 0.0]

In [30]:
A = matrix(RDF, [[1,2],[3,4],[5,6],[7,8]])

In [31]:
th = 0.7 
R = matrix(RDF, [[cos(th),sin(th)],[-sin(th),cos(th)]]) 
B = (A + 0.1*random_matrix(RDF,4,2)) * transpose(R)

In [32]:
C = transpose(B)*A 
U, Sigma, V = C.SVD() 
Q = U*transpose(V)

In [33]:
Q

[0.7657221742194118 0.6431714793961997]
[  -0.6431714793962  0.765722174219412]

In [34]:
R

[0.7648421872844885  0.644217687237691]
[-0.644217687237691 0.7648421872844885]

In [36]:
n = 10 
A = random_matrix(RDF, n); 
A = A*transpose(A) # A vérifie (presque sûrement) les hypothèses
x = vector(RDF, [1 for i in range(0,n)]) 
for i in range(0,1000): 
    y = A*x 
    z = y/y.norm()
    lam = z*y 
    s = (x-z).norm() 
    print i, "\ts=", s, "\tlambda=", lam 
    if s < 1e-10: break 
    x=z

0 	s= 2.33042955065 	lambda= 17.4188386771
1 	s= 0.223510705141 	lambda= 6.82639359114
2 	s= 0.251574387277 	lambda= 7.65976606259
3 	s= 0.237922762246 	lambda= 8.68290995435
4 	s= 0.181905605835 	lambda= 9.51183807692
5 	s= 0.121454839122 	lambda= 9.96788766713
6 	s= 0.076062246562 	lambda= 10.165700015
7 	s= 0.0464398640208 	lambda= 10.2424757184
8 	s= 0.0281007885849 	lambda= 10.2709973224
9 	s= 0.0169589267465 	lambda= 10.2814323943
10 	s= 0.0102317593631 	lambda= 10.2852338669
11 	s= 0.00617661534085 	lambda= 10.2866184292
12 	s= 0.00373197899726 	lambda= 10.2871233586
13 	s= 0.00225719721387 	lambda= 10.2873078387
14 	s= 0.00136666504831 	lambda= 10.2873753789
15 	s= 0.000828370074987 	lambda= 10.287400159
16 	s= 0.000502640940788 	lambda= 10.2874092703
17 	s= 0.00030532361666 	lambda= 10.2874126278
18 	s= 0.000185663891307 	lambda= 10.2874138676
19 	s= 0.000113019231673 	lambda= 10.2874143264
20 	s= 6.88694449149e-05 	lambda= 10.2874144966
21 	s= 4.20087677551e-05 	lambda= 10.28

In [37]:
A.eigenvalues()

[10.28741459736515,
 6.379993918252768,
 6.08897600855732,
 4.540487995305153,
 2.8495562316799603,
 2.126894392768425,
 0.8841097423675887,
 0.5422909517857157,
 0.020289414533476543,
 0.09961443962273524]

In [38]:
A = matrix(RDF, [[1,3,2],[1,2,3],[0,5,2]])

In [39]:
mu = 0.50519 
AT = A - mu*identity_matrix(RDF, 3) 
x = vector(RDF, [1 for i in range(0,A.nrows())]) 
P, L, U = AT.LU() 
for i in range(1,10):
    y = AT.solve_right(x) 
    x = y/y.norm() 
    lamb = x*A*x 
    print x, lamb

(0.9607985552565431, 0.18570664546988727, -0.2058620364352333) 1.08914936279
(0.927972943625375, 0.1044861051800865, -0.3576994125289455) 0.563839629189
(0.9276916133832703, 0.10329827357690813, -0.35877254233619243) 0.560558807639
(0.9276845318283404, 0.10329496332009931, -0.35879180586954856) 0.560519659839
(0.9276845648427788, 0.1032947552966817, -0.3587917803972978) 0.560519482021
(0.9276845629124328, 0.10329475732310033, -0.3587917848049623) 0.560519476073
(0.9276845629447148, 0.10329475725254855, -0.3587917847418061) 0.560519476114
(0.9276845629438836, 0.1032947572539018, -0.3587917847435661) 0.560519476112
(0.9276845629439012, 0.10329475725386913, -0.35879178474352963) 0.560519476112


In [40]:
m = matrix(RDF, [[1,2,3,4],[1,0,2,6],[1,8,4,-2],[1,5,-10,-20]]) 
Aref = transpose(m)*m
A = copy(Aref) 
for i in range(0,20): 
    Q, R = A.QR() 
    A = R*Q 
    print A.str(lambda x: RealField(30)(x).str())

[    347.58031    -222.89331    -108.24117  -0.067928252]
[   -222.89331     243.51949     140.96827   0.081743964]
[   -108.24117     140.96827     90.867499 -0.0017822044]
[ -0.067928252   0.081743964 -0.0017822044   0.032699348]
[    574.27341    -71.947796    -1.2834205  5.1350507e-6]
[   -71.947796     103.59833     2.6822418 -8.5884756e-6]
[   -1.2834205     2.6822418     4.0959873 0.00032664633]
[ 5.1350508e-6 -8.5884756e-6 0.00032664633   0.032266936]
[     584.75334     -11.676748  -0.0089243355 -2.8618608e-10]
[    -11.676748      93.191354     0.10696740   2.6947928e-9]
[ -0.0089243355     0.10696740      4.0230378  -2.6208083e-6]
[-2.8628619e-10   2.6947881e-9  -2.6208083e-6    0.032266909]
[      585.02356      -1.8555147 -0.000061384282  -8.4197985e-14]
[     -1.8555147       92.921261    0.0046211636  -9.3995573e-13]
[-0.000061384282    0.0046211636       4.0229097    2.1020987e-8]
[  1.5794231e-14  -9.3327923e-13    2.1020961e-8     0.032266909]
[     585.03038    -0.29

In [41]:
Aref.eigenvalues()

[585.0305586200212, 92.91426499150643, 0.03226690899408103, 4.022909479477674]

# La décomposition en valeurs singulières

On considère une matrice rectangulaire à coefficients dans $\bf R$. Tracez l'image qui lui corresponde. 

In [17]:
from __future__ import print_function
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

In [18]:
def f(x):
    return x

In [19]:
interact(f, x=10)

10

<function f at 0x7f63a39e30c8>

In [20]:
interact(f, x=True)

True

<function f at 0x7f63a39e30c8>

In [21]:
@interact(x=True, y=1.0)
def g(x, y):
    return (x, y)

(True, 1.0)

In [22]:
interact(f, x=['apples','oranges']);

'apples'

In [23]:
from IPython.display import display
def f(a, b):
    display(a + b)
    return a+b

In [24]:
w = interactive(f, a=10, b=20)

In [25]:
display(w)

30

In [26]:
%matplotlib inline
from ipywidgets import interactive
import matplotlib.pyplot as plt
import numpy as np

def f(m, b):
    plt.figure(2)
    x = np.linspace(-10, 10, num=1000)
    plt.plot(x, m * x + b)
    plt.ylim(-5, 5)
    plt.show()

interactive_plot = interactive(f, m=(-2.0, 2.0), b=(-3, 3, 0.5))
output = interactive_plot.children[-1]
output.layout.height = '350px'
interactive_plot

In [29]:
widgets.IntSlider()

Widget Javascript not detected.  It may not be installed or enabled properly.


In [2]:
A1 = matrix(2,3, [3,1,1, -1,3,1])
A2 = matrix(2,3, [4,1,1, -1,4,1])
A3 = matrix(2,3, [2,1,1, -1,2,1])

In [3]:
matrix_plot(A2)

#### Question 1 : Calculez une base de vecteurs propres de $A.A^t$ et de $A^t.A$.

In [4]:
A = A1
B = A*transpose(A)
show(B)

In [5]:
b = B.eigenspaces_left()
b[0], b[1]

((12, Vector space of degree 2 and dimension 1 over Rational Field
  User basis matrix:
  [1 1]), (10, Vector space of degree 2 and dimension 1 over Rational Field
  User basis matrix:
  [ 1 -1]))

In [6]:
b = B.eigenspaces_right()
b

[
(12, Vector space of degree 2 and dimension 1 over Rational Field
User basis matrix:
[1 1]),
(10, Vector space of degree 2 and dimension 1 over Rational Field
User basis matrix:
[ 1 -1])
]

In [7]:
#help(B.eigenvectors_left)

#### Question 2 : Notez $U$ (respectivement $V$) la matrice de la base orthonormée formée des vecteurs propres de $A.A^t$ (respectivement de $A.A$). Notez $D$ la matrice des valeurs singulières de $A$. Trouvez une manière rapide pour générer $U$,$V$ et $D$. 

In [8]:
norm(vector([1,1]))

sqrt(2)

In [9]:
U = matrix(RR,2,2, [1/sqrt(2), 1/sqrt(2), 1/sqrt(2), -1/sqrt(2)])
show(U)

In [10]:
D = matrix(RR,2,3,[sqrt(12),0,0, 0,sqrt(10),0])
show(D)

In [11]:
C = transpose(A)*A
show(C)

In [12]:
C.eigenspaces_left()

[
(12, Vector space of degree 3 and dimension 1 over Rational Field
User basis matrix:
[1 2 1]),
(10, Vector space of degree 3 and dimension 1 over Rational Field
User basis matrix:
[   1 -1/2    0]),
(0, Vector space of degree 3 and dimension 1 over Rational Field
User basis matrix:
[ 1  2 -5])
]

In [13]:
V = matrix(RR, 3,3, [1/sqrt(6),2/sqrt(5),1/sqrt(30), 2/sqrt(6),-1/sqrt(5),2/sqrt(30), 1/sqrt(6),0,-5/sqrt(30)])
show(V)

In [14]:
(U * D) * transpose(V)

[ 3.00000000000000  1.00000000000000  1.00000000000000]
[-1.00000000000000  3.00000000000000  1.00000000000000]

In [15]:
A

[ 3  1  1]
[-1  3  1]

In [16]:
import numpy
u, s, v = numpy.linalg.svd(A3)

In [17]:
u, s, v

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([ 2.64575131,  2.23606798]),
 array([[ -2.67261242e-01,  -8.01783726e-01,  -5.34522484e-01],
        [ -9.48683298e-01,   3.16227766e-01,  -4.95252351e-16],
        [ -1.69030851e-01,  -5.07092553e-01,   8.45154255e-01]]))

In [18]:
#from reseau import perceptron

In [19]:
norm(vector([1,2]))

sqrt(5)

#### Question 3 : Importez l'image coffee.png et stockez-là dans une matrice `A_image`.

In [20]:
import numpy
import pylab
A_image = 1-numpy.mean(pylab.imread('coffee.png'),2)
A_image.shape

(400, 600)

In [21]:
B = pylab.imread('coffee.png')
B.shape

(400, 600, 3)

In [22]:
#help(numpy.mean)

In [23]:
matrix_plot(A_image)

#### Question 4 : Tracez sur un même graphique la matrice `A_image` ainsi que la matrice `A_approx` qui donne une approximation de l'image en fonction d'un nombre de valeurs singulières réduit.

In [24]:
U,s,V = numpy.linalg.svd(A_image)

In [25]:
A_image[0,0]

0.94509804

In [26]:
A_image.shape

(400, 600)

In [27]:
D = numpy.zeros(A_image.shape)
D[:len(s),:len(s)] = numpy.diag(s)

In [28]:
s[0:20], len(s)

(array([ 305.42077637,   61.69586563,   32.93205643,   25.52998352,
          20.38374138,   16.9603672 ,   15.35072994,   13.72278023,
          11.87147045,   10.67421055,   10.001894  ,    9.39233875,
           8.76823997,    7.74965048,    6.84282398,    6.744205  ,
           6.53583384,    6.15535498,    5.86225843,    5.41834593], dtype=float32),
 400)

In [29]:
import matplotlib.pyplot as plt
plt.hist(s[0:30], bins='auto')
#help(plt.hist)

(array([ 18.,   5.,   2.,   1.,   1.,   1.,   0.,   0.,   0.,   0.,   1.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   1.]),
 array([   4.04660654,    9.33387268,   14.62113882,   19.90840495,
          25.19567109,   30.48293723,   35.77020336,   41.0574695 ,
          46.34473564,   51.63200178,   56.91926791,   62.20653405,
          67.49380019,   72.78106633,   78.06833246,   83.3555986 ,
          88.64286474,   93.93013087,   99.21739701,  104.50466315,
         109.79192929,  115.07919542,  120.36646156,  125.6537277 ,
         130.94099384,  136.22825997,  141.51552611,  146.80279225,
         152.09005839,  157.37732452,  162.66459066,  167.9518568 ,
         173.23912293,  178.52638907,  183.81365521,  189.100921

In [30]:
from sage.plot.histogram import Histogram
H = histogram(s, bins=10, normed=False, range=[0,40])
show(H)

In [31]:
help(histogram)

Help on function histogram in module sage.plot.histogram:

histogram(*args, **kwds)
    Computes and draws the histogram for list(s) of numerical data.
    See examples for the many options; even more customization is
    available using matplotlib directly.
    
    INPUT:
    
    - ``datalist`` -- A list, or a list of lists, of numerical data
    - ``align`` -- (default: "mid") How the bars align inside of each bin.
      Acceptable values are "left", "right" or "mid"
    - ``alpha`` -- (float in [0,1], default: 1) The transparency of the plot
    - ``bins`` -- The number of sections in which to divide the range. Also
      can be a sequence of points within the range that create the
      partition
    - ``color`` -- The color of the face of the bars or list of colors if
      multiple data sets are given
    - ``cumulative`` -- (boolean - default: False) If True, then
      a histogram is computed in which each bin gives the counts in that
      bin plus all bins for smaller value

In [38]:
i = 60
A_approx = numpy.dot(numpy.dot(U[:,:i], D[:i,:i]), V[:i,:])
graphics_array([matrix_plot(A_image), matrix_plot(A_approx)])

In [33]:
(60*(400+600+1))/(400*600).n()

0.250250000000000

In [34]:
import numpy
import pylab
B_image = 1-numpy.mean(pylab.imread('test.png'), 2)
matrix_plot(B_image)

In [35]:
A = 1-pylab.imread('test.png')
A.shape

(585, 952, 4)

In [79]:
B_image.shape

(585, 952)

In [80]:
U,s,V = numpy.linalg.svd(B_image)

In [81]:
D = numpy.zeros(B_image.shape)
D[:len(s),:len(s)] = numpy.diag(s)

In [82]:
i = 15
B_approx = numpy.dot(numpy.dot(U[:,:i], D[:i,:i]), V[:i,:])
graphics_array([matrix_plot(B_image), matrix_plot(B_approx)])

In [83]:
i = 100
A_approx = numpy.dot(numpy.dot(U[:,:i], D[:i,:i]), V[:i,:])
graphics_array([matrix_plot(B_image), matrix_plot(A_approx)])

In [1]:
#http://www.math.univ-toulouse.fr/~besse/Wikistat/pdf/st-scenar-explo1-svd-acp.pdf

In [2]:
# Matrice des données - Traitement sur R
note=matrix(c(6,6,5,5.5,8,8,8,8,6,7,11,9.5,14.5,14.5,15.5,15,14,1,12,12.5,11,10,5.5,7,5.5,7,14,11.5,13,12.5,8.5,9.5,9,9.5,12.5,12),nrow=9,byrow=TRUE)

In [3]:
note=data.frame(note)

In [4]:
nomi=c("Salah","Ali","Besma","Amina",
"Marwen","Slim","Faten","Fatma","Essia")
nomv=c("Math","Phys","Fran","Angl")
dimnames(note)[[1]]=nomi
dimnames(note)[[2]]=nomv
# Vérification
note

Math Phys Fran Angl 
 
 Salah 6.0 6.0 5.0 5.5 
 Ali 8.0 8.0 8.0 8.0 
 Besma 6.0 7.0 11.0 9.5 
 Amina 14.5 14.5 15.5 15.0 
 Marwen 14.0 1.0 12.0 12.5 
 Slim 11.0 10.0 5.5 7.0 
 Faten 5.5 7.0 14.0 11.5 
 Fatma 13.0 12.5 8.5 9.5 
 Essia 9.0 9.5 12.5 12.0

In [5]:
summary(note)

      Math             Phys             Fran            Angl      
 Min.   : 5.500   Min.   : 1.000   Min.   : 5.00   Min.   : 5.50  
 1st Qu.: 6.000   1st Qu.: 7.000   1st Qu.: 8.00   1st Qu.: 8.00  
 Median : 9.000   Median : 8.000   Median :11.00   Median : 9.50  
 Mean   : 9.667   Mean   : 8.389   Mean   :10.22   Mean   :10.06  
 3rd Qu.:13.000   3rd Qu.:10.000   3rd Qu.:12.50   3rd Qu.:12.00  
 Max.   :14.500   Max.   :14.500   Max.   :15.50   Max.   :15.00  

In [6]:
boxplot(note)

In [7]:
X=as.matrix(note)
# Matrice des variances covariances
var(X)

Math Phys Fran Angl 
 
 Math 12.812500 4.114583 2.989583 5.427083 
 Phys 4.114583 15.298611 1.746528 2.194444 
 Fran 2.989583 1.746528 13.569444 10.454861 
 Angl 5.427083 2.194444 10.454861 8.902778

In [7]:
# Matrice des corrélations
cor(X)

Math Phys Fran Angl 
 
 Math 1.0000000 0.2938887 0.2267319 0.5081440 
 Phys 0.2938887 1.0000000 0.1212184 0.1880338 
 Fran 0.2267319 0.1212184 1.0000000 0.9512058 
 Angl 0.5081440 0.1880338 0.9512058 1.0000000

In [8]:
# Matrice centrée
Xb=scale(X,scale=F)
Xb

Math Phys Fran Angl 
 
 Salah -3.6666667 -2.3888889 -5.2222222 -4.5555556 
 Ali -1.6666667 -0.3888889 -2.2222222 -2.0555556 
 Besma -3.6666667 -1.3888889 0.7777778 -0.5555556 
 Amina 4.8333333 6.1111111 5.2777778 4.9444444 
 Marwen 4.3333333 -7.3888889 1.7777778 2.4444444 
 Slim 1.3333333 1.6111111 -4.7222222 -3.0555556 
 Faten -4.1666667 -1.3888889 3.7777778 1.4444444 
 Fatma 3.3333333 4.1111111 -1.7222222 -0.5555556 
 Essia -0.6666667 1.1111111 2.2777778 1.9444444

In [9]:
# Covariance
S=t(Xb)%*%Xb/8
S

Math Phys Fran Angl 
 
 Math 12.812500 4.114583 2.989583 5.427083 
 Phys 4.114583 15.298611 1.746528 2.194444 
 Fran 2.989583 1.746528 13.569444 10.454861 
 Angl 5.427083 2.194444 10.454861 8.902778

In [10]:
# SVD
res=svd(Xb)
res

$d 
 
 14.5488526595632 
 10.9154770279556 
 8.58063974258191 
 0.471737021215316 
 
 
 $u 
 
 
 -0.56111468 -0.06559919 -0.01213540 -0.19436462 
 -0.23055617 -0.07488867 -0.04834359 0.05942450 
 -0.13970087 0.20775306 -0.30822765 0.28867867 
 0.70927433 -0.22629485 -0.07574595 0.06549936 
 0.11332658 0.58106138 0.73303165 0.02323628 
 -0.22524932 -0.42214127 0.23416428 0.01481155 
 0.04254077 0.39324932 -0.47791916 0.31803529 
 0.11801095 -0.46856042 0.17148770 0.26173128 
 0.17346841 0.07542064 -0.21631188 -0.83705231 
 
 
 
 $v 
 
 
 0.4586820 -0.2552142 0.82569422 0.206653284 
 0.3695920 -0.8105760 -0.45423155 -0.006481091 
 0.5976476 0.4550468 -0.33387138 0.569455627 
 0.5439025 0.2660164 -0.02080026 -0.795595817

In [11]:
# Matrices des vecteurs propres
U=res$u;V=res$v

In [12]:
# Valeurs propres et variance expliquée
L=res$d*res$d/8; pct=L/sum(L)
L;pct

26.45863921371 
 14.8934548434782 
 9.20342229899703 
 0.0278169771481375

0.523070297470379 
 0.294434033149486 
 0.181945745614439 
 0.000549923765696292

In [13]:
#Composantes principales
C=Xb%*%V
C

Salah -8.1635748 -0.7160464 -0.1041295 -0.091688988 
 Ali -3.3543278 -0.8174455 -0.4148189 0.028032737 
 Besma -2.0324873 2.2677237 -2.6447904 0.136180414 
 Amina 10.3191277 -2.4701163 -0.6499487 0.030898475 
 Marwen 1.6487717 6.3425621 6.2898805 0.010961413 
 Slim -3.2771191 -4.6078734 2.0092794 0.006987157 
 Faten 0.6189194 4.2925039 -4.1008522 0.150029018 
 Fatma 1.7169239 -5.1145605 1.4714741 0.123468336 
 Essia 2.5237663 0.8232523 -1.8560943 -0.394868563

In [14]:
boxplot(as.data.frame(C))

In [15]:
# Coordonnées "isométriques lignes"
plot(C,type="n")
text(C,nomi)
abline(h=0,v=0)

In [16]:
# Coordonnées "isométriques colonnes"
plot(V[,1]*sqrt(L[1]),V[,2]*sqrt(L[2]),
type="n")
text(V[,1]*sqrt(L[1]),V[,2]*sqrt(L[2]),
nomv)
abline(h=0,v=0)

In [17]:
res1.acp=princomp(note)
summary(res1.acp)
plot(res1.acp)
biplot(res1.acp)

Importance of components:
                          Comp.1    Comp.2    Comp.3       Comp.4
Standard deviation     4.8496176 3.6384923 2.8602132 0.1572456737
Proportion of Variance 0.5230703 0.2944340 0.1819457 0.0005499238
Cumulative Proportion  0.5230703 0.8175043 0.9994501 1.0000000000

In [18]:
res2.acp=prcomp(note)
summary(res2.acp)
plot(res2.acp)
biplot(res2.acp)

Importance of components%s:
                          PC1    PC2    PC3     PC4
Standard deviation     5.1438 3.8592 3.0337 0.16678
Proportion of Variance 0.5231 0.2944 0.1820 0.00055
Cumulative Proportion  0.5231 0.8175 0.9994 1.00000