In [5]:
A = matrix(4,4, [10,7,8,7, 7,5,6,5, 8,6,10,9, 7,5,9,10])
A

[10  7  8  7]
[ 7  5  6  5]
[ 8  6 10  9]
[ 7  5  9 10]

In [6]:
A.norm()*A.inverse().norm()

2984.09270167549

In [7]:
b = vector([32,23,33,31])
x = A.solve_right(b)
x

(1, 1, 1, 1)

In [8]:
DA = matrix(4,4,[0.01,-0.01,0.02,0.03, 0,0,0.1,0.02, -0.02,0,0,-0.01, 0,0,0.1,0])
db = vector([0.01,-0.01,0,0.02])

In [10]:
(A+DA).solve(b+db)

(-11.7491044400966, 22.3927907427797, -4.81963106890252, 4.51584200937903)

### Question :
Comment rendre ces deux perturbations aléatoires (perturbation comprise entre -0.01 et 0.02) ?

In [14]:
import random
A + 0.01*random_matrix(ZZ,4,4)

[9.99000000000000 6.99000000000000 7.92000000000000 7.01000000000000]
[7.00000000000000 4.99000000000000 6.00000000000000 5.03000000000000]
[7.99000000000000 6.01000000000000 10.0200000000000 9.04000000000000]
[7.02000000000000 5.00000000000000 9.00000000000000 10.0100000000000]

In [15]:
db = vector([32+uniform(-0.01,0.02),23+uniform(-0.01,0.02),33+uniform(-0.01,0.02),31+uniform(-0.01,0.02)])
db

(32.0068735183810, 23.0001857313602, 32.9912498689971, 30.9998685436741)

In [16]:
db = b+0.01*random_vector(4)

In [18]:
xdx = (A+DA).solve_right(b+db)
xdx

(-21.7182370631160, 41.7818083580945, -8.76476590261969, 8.48479873651788)

In [1]:
A = matrix(3,3, [3,2,1, 1,0,0, 0,0,1])
A

[3 2 1]
[1 0 0]
[0 0 1]

In [2]:
A.LU()

(
[1 0 0]  [  1   0   0]  [   3    2    1]
[0 1 0]  [1/3   1   0]  [   0 -2/3 -1/3]
[0 0 1], [  0   0   1], [   0    0    1]
)

### LU - Cholesky - Jacobi.

In [6]:
A = matrix(4,4, [1,0,6,2, 8,0,-2,-2, 2,9,1,3, 2,1,-3,10])

In [7]:
show(A)

In [0]:
A.LU()

In [10]:
S = A.LU()

In [16]:
S[0]*A

[ 2  9  1  3]
[ 1  0  6  2]
[ 8  0 -2 -2]
[ 2  1 -3 10]

In [17]:
A.inverse()

[115/2491 289/2491  -4/2491  36/2491]
[-98/2491 -81/4982 285/2491 -74/2491]
[364/2491 -55/4982   9/2491 -81/2491]
[ 96/2491 -62/2491 -25/2491 225/2491]

In [20]:
#help(A.LU)

In [21]:
A

[ 2  9  1  3]
[ 1  0  6  2]
[ 8  0 -2 -2]
[ 2  1 -3 10]

In [23]:
S[0]*S[1]*S[2]

[ 1  0  6  2]
[ 8  0 -2 -2]
[ 2  9  1  3]
[ 2  1 -3 10]

In [25]:
S[0].inverse()*A

[ 8  0 -2 -2]
[ 2  9  1  3]
[ 1  0  6  2]
[ 2  1 -3 10]

In [26]:
S[1]*S[2]

[ 8  0 -2 -2]
[ 2  9  1  3]
[ 1  0  6  2]
[ 2  1 -3 10]

In [2]:
n = 4
A = matrix(n,n,[1/(i+j-1) for i in range(1, n+1) for j in range(1, n+1)])
b = [1 for i in range(n)]
show(A)
show(b)
norm(A)*norm(A.inverse())

15513.73873893259

In [3]:
import numpy
numpy.linalg.solve(A,b)

array([  -4.,   60., -180.,  140.])

In [4]:
b = [1,0.99,1,0.99]
numpy.linalg.solve(A,b)

array([  -1.4,   31.2, -111. ,   95.2])

In [5]:
A = matrix(4,4,[7,1,11,10, 2,6,5,2, 8,11,3,8, 6,9,3,6])
b = [29,15,30,24]
numpy.linalg.solve(A,b)

array([ 1.,  1.,  1.,  1.])

In [6]:
bprim = [29.1, 14.9, 30.1, 23.9]
numpy.linalg.solve(A,bprim)

array([ 6.22222222,  0.13333333,  1.63333333, -3.25555556])

In [7]:
norm(A)*norm(A.inverse())

1424.950271129373

In [20]:
A = matrix(4,4, [10,7,8,7, 7,5,6,5, 8,6,10,9, 7,5,9,10])
A

[10  7  8  7]
[ 7  5  6  5]
[ 8  6 10  9]
[ 7  5  9 10]

In [21]:
norm(A)*norm(A.inverse())

2984.09270167549

In [22]:
C = diagonal_matrix([1/10,1/5,1/10,1/10])
C

[1/10    0    0    0]
[   0  1/5    0    0]
[   0    0 1/10    0]
[   0    0    0 1/10]

In [23]:
Ap = C*A
Ap

[   1 7/10  4/5 7/10]
[ 7/5    1  6/5    1]
[ 4/5  3/5    1 9/10]
[7/10  1/2 9/10    1]

In [24]:
norm(Ap)*norm(Ap.inverse())

2484.760853054217

In [26]:
A.LU()

(
[1 0 0 0]  [   1    0    0    0]  [  10    7    8    7]
[0 0 0 1]  [ 4/5    1    0    0]  [   0  2/5 18/5 17/5]
[0 1 0 0]  [7/10  1/4    1    0]  [   0    0  5/2 17/4]
[0 0 1 0], [7/10  1/4 -1/5    1], [   0    0    0 1/10]
)

### Exercice.
Ecrire un algorithme qui permet de factoriser A en L et U. E déduire la complexité de ce calcul en fonction de la taille de A.

In [9]:
A.is_symmetric()

False

In [10]:
A.is_positive_definite()

False

In [13]:
#A.cholesky()

In [14]:
R = matrix(QQ, 5,5, [ 0,0,0,0,1, 1,1,1,1,1, 16,8,4,2,1, 81,27,9,3,1, 256,64,16,4,1 ])
show(R)

In [15]:
A = R*transpose(R)
latex(A)

\left(\begin{array}{rrrrr}
1 & 1 & 1 & 1 & 1 \\
1 & 5 & 31 & 121 & 341 \\
1 & 31 & 341 & 1555 & 4681 \\
1 & 121 & 1555 & 7381 & 22621 \\
1 & 341 & 4681 & 22621 & 69905
\end{array}\right)

In [16]:
u = A.cholesky()
u

[                 1                  0                  0                  0                  0]
[                 1                  2                  0                  0                  0]
[                 1                 15 10.72380529476361?                  0                  0]
[                 1                 60 60.98581445891652? 7.792973423707327?                  0]
[                 1                170 198.6235241551869? 39.36656677955248? 1.723099580682572?]

In [17]:
u*transpose(u)

[                 1                  1                  1                  1                  1]
[                 1                  5                 31                121                341]
[                 1                 31 341.0000000000000? 1555.000000000000? 4681.000000000000?]
[                 1                121 1555.000000000000? 7381.000000000000? 22621.00000000000?]
[                 1                341 4681.000000000000? 22621.00000000000?  69905.0000000000?]

In [36]:
def cholesky(A):
    if A.is_square()==False:
        return("la marice A n est pas carre")
    if A.is_symmetric()==False:
        return("la marice A n est pas symetrique")
    if A.is_positive_definite()==False:
        return("la marice A n est pas definie positive")
    n = A.ncols()
    R = matrix(RR,n,n)
    R[0,0] = sqrt(A[0,0])
    for i in range(1,n):
        for j in range(i):
            R[i,j] = 1/R[j,j]*(A[i,j]-add([R[i,k]*R[j,k] for k in range(j)]))
        R[i,i] = sqrt(A[i,i]-add([R[i,k]^2 for k in range(i)])) 
    print R*transpose(R)   
    return(R)

In [0]:
RealField?

In [37]:
A = matrix(3,3,[1,1,1, 1,3,7, 1,7,21])
cholesky(A)

[1.00000000000000 1.00000000000000 1.00000000000000]
[1.00000000000000 3.00000000000000 7.00000000000000]
[1.00000000000000 7.00000000000000 21.0000000000000]


[ 1.00000000000000 0.000000000000000 0.000000000000000]
[ 1.00000000000000  1.41421356237310 0.000000000000000]
[ 1.00000000000000  4.24264068711928  1.41421356237310]

In [8]:
A = matrix(3,3,[i+j+1 for i in range(3) for j in range(3)])
A

[1 2 3]
[2 3 4]
[3 4 5]

In [9]:
A.eigenvalues()

[0, -0.623475382979800?, 9.623475382979799?]

### Méthodes itératives

Il s’agit de résoudre un système d’équation linéaires par les méthodes développées précédemment (LU, Cholesky, Jacobi, Gradient conjugué).
1. Ecrire les algorithmes de descentes puis de remontée appliqués à des matrices triangulaires (respectivement inférieures et supérieures)

2. Résoudre le système d’équations linéaires Ax = b avec $A=$ et $b=$.
    1. Vérifiez que A est symétrique définie-positive.
    2. Calculez la factorisation de Cholesky de A puis résoudre le système $Ax = b$.

3. La méthode de Jacobi consiste à calculer la suite $x_{k+1} = Jx_k +D^{-1}b$ avec $J = I_n -D^{-1}A$ et $D$ la matrice diagonale contenant les éléments de la diagonale de $A$. Appliquez la méthode de Jacobi, en partant de $x0=(2,2,2)$. Vous remarquerez que $x_2 = x^*$ la
solution du système $Ax = b$.

4. Résoudre le système $Ax = b$ grâce à la factorisaton de Cholesky puis grâce à la méthode de Jacobi, avec $x_0=(2,2,2)$.

In [29]:
A = matrix(2,2,[2,-1,-1,2])

In [30]:
b = vector([1,1])

In [31]:
A.diagonal()

[2, 2]

In [32]:
D = diagonal_matrix(A.diagonal())

In [33]:
J = identity_matrix(2)-D.inverse()*A

In [34]:
x0 = vector([0,0])
J*x0 + D.inverse()*b

(1/2, 1/2)

In [35]:
for i in range(5):
    x1 = J*x0 + D.inverse()*b
    x0 = x1.n()
print(x1)

(0.968750000000000, 0.968750000000000)


In [27]:
A.solve_left(b)

(1, 1)

In [28]:
J.eigenvalues()

[1/2, -1/2]